fmod BOOLEAN is
    sort Boolean .
    ops true false : -> Boolean [ctor] .
    op not_ : Boolean -> Boolean [prec 53] .
    op _and_ : Boolean Boolean -> Boolean [prec 55] .
    op _or_ : Boolean Boolean -> Boolean [prec 59] .

    var B : Boolean .
    eq not_(false) = true .
    eq not_(true) = false .
    eq (true and B) = B .
    eq (false and B) = false .
    eq (false or B) = B .
    eq (true or B) = true .
endfm
       
    
